# group_vars/all.yml
# Variables visible to all nodes
---

rhbase_install_packages:
  - bash-completion
  - bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget
# ansible_ssh_private_key_file: "/opt/test123.pem"