---
galaxy_info:
  author: Mariusz Czyz
  description: CentOS 7 Rainloop Webmail Installation Role
  license: BSD
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - centos
    - rainloop
    - webmail
