 echo Install needed SQL
 pause
#Enable-ADAccount svcSQL
 C:\Sources\SQL2016\Setup.exe /qs /ACTION=Install /FEATURES=SQL,RS,Tools /INSTANCENAME=MSSQLSERVER /SQLSVCACCOUNT="CORONA2020.local\Administrator" /SQLSVCPASSWORD="P@ssw0rd" /SQLSYSADMINACCOUNTS="CORONA2020.local\Domain Admins" /AGTSVCACCOUNT="NT AUTHORITY\Network Service" /IACCEPTSQLSERVERLICENSETERMS /SQLCOLLATION=SQL_Latin1_General_CP1_CI_AS
