# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_firewall_allow_ports:
  - 10051/tcp
rhbase_install_packages:
  - bash-completion
  - bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget
zabbix_agent_server: 192.168.10.196
zabbix_agent_serveractive: 192.168.10.196
zabbix_url: http://zabbix.corona2020.local
zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
zabbix_api_user: Admin
zabbix_api_pass: zabbix
zabbix_create_host: present
zabbix_host_groups:
  - Linux Servers
zabbix_link_templates:
  - Template OS Linux
  - Apache APP Template
zabbix_macros:
  - macro_key: apache_type
    macro_value: reverse_proxy